apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertx-auction
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertx-auction
  template:
    metadata:
      labels:
        app: vertx-auction
    spec:
      securityContext:
            runAsUser: 0
      containers:
        - name: vertx-auction
          image: mohamedfazil/vertx-auction:main-d9f9c55
          command: ["./gradlew","run","--debug"]
          ports:
          - name: httpport
            containerPort: 8080
          
